apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanastra-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kanastra-node-app
  template:
    metadata:
      labels:
        app: kanastra-node-app
    spec:
      containers:
        - name: kanastra-node-app
          image: kanastra-node-app:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health/check
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/check
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
